version: "3"

services:
 app:
  build:
   context: ./src
  ports:
   - "5000:5000"
  volumes:
   - ./src:/src
  command: >
   sh -c "python manage.py runserver"
  environment:
   - DB_HOST=db
   - DB_NAME=app
   - DB_USER=postgres
   - DB_PASS=supersecretpassword
  depends_on:
   - mongo
  env_file:
   - docker.env

 mongo:
  image: mongo
  restart: always
  ports:
    - "27017:27017"
  environment:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: secret
    MONGO_INITDB_DATABASE: mydb
  volumes:
    - mongo-data:/data/db

 mongo-express:
  image: mongo-express
  restart: always
  ports:
    - "8081:8081"
  environment:
    ME_CONFIG_MONGODB_ADMINUSERNAME: root
    ME_CONFIG_MONGODB_ADMINPASSWORD: secret

volumes:
  mongo-data: